trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  configuration: debug
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)
  displayName: 'dotnet build $(buildConfiguration)'
  
- task: CopyFiles@2
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)' 

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'myWebsiteName'